name: Release

on:
  workflow_dispatch:
    branches:
      - master
    inputs:
      semver:
        description: 'Release Semantic Versioning (e.g. 4.15.2)'
        required: true

jobs:
  build-release:
    name: Build release
    runs-on: ubuntu-latest
    timeout-minutes: 20
    env:
      TERM: dumb

    steps:
      - name: Checkout
        uses: actions/checkout@v2

      - name: Create release tag
        uses: actions/github-script@v5
        with:
          github-token: ${{ secrets.GITHUB_TOKEN }}
          script: |
            github.rest.git.createRef({
              owner: context.repo.owner,
              repo: context.repo.repo,
              ref: "refs/tags/${{ github.event.inputs.semver }}",
              sha: context.sha
            })

      - name: Workaround to fetch the tag # Is there a better way to do it?
        uses: actions/checkout@v2
        with:
          fetch-depth: 0

      - name: Setup JDK 11.0.10
        uses: actions/setup-java@v2
        with:
          distribution: 'adopt'
          java-version: 11.0.10

      - name: Copy CI gradle.properties
        run: mkdir -p ~/.gradle ; cp .github/ci-gradle.properties ~/.gradle/gradle.properties

      - name: Validate gradle wrapper
        uses: gradle/wrapper-validation-action@v1

      - name: Decrypt secrets
        run: ./release/decrypt-secrets.sh
        env:
          ENCRYPT_KEY: ${{ secrets.ENCRYPT_KEY }}

      ## Actual task
      - name: Build
        uses: gradle/gradle-build-action@v2
        env:
          ORG_GRADLE_PROJECT_RELEASE_KEYSTORE_PWD: ${{ secrets.RELEASE_KEYSTORE_PWD }}
        with:
          arguments: assemble bundle

      - name: Publish to Play Store
        uses: gradle/gradle-build-action@v2
        env:
          ORG_GRADLE_PROJECT_RELEASE_KEYSTORE_PWD: ${{ secrets.RELEASE_KEYSTORE_PWD }}
        with:
          arguments: publishBundle

      - name: Clean secrets
        if: always()
        run: ./release/clean-secrets.sh

      - name: Upload build outputs
        if: always()
        uses: actions/upload-artifact@v2
        with:
          name: build-outputs
          path: app/build/outputs

      - name: Create GitHub release
        uses: softprops/action-gh-release@v1
        with:
          draft: true
          tag_name: ${{ github.event.inputs.semver }}
          fail_on_unmatched_files: true
          files: |
            app/build/outputs/apk/debug/forlago-debug.apk
            app/build/outputs/apk/release/forlago-release.apk
            app/build/outputs/bundle/debug/forlago-debug.aab
            app/build/outputs/bundle/release/forlago-release.aab
            app/build/outputs/mapping/release/mapping.txt
        env:
          GITHUB_TOKEN: ${{ secrets.GITHUB_TOKEN }}

      - name: Delete release tag
        if: failure()
        uses: actions/github-script@v5
        with:
          github-token: ${{ secrets.GITHUB_TOKEN }}
          script: |
            github.rest.git.deleteRef({
              owner: context.repo.owner,
              repo: context.repo.repo,
              ref: "tags/${{ github.event.inputs.semver }}"
            })
